#ifndef CONFIG_LOG_CONFIG_H_
#define CONFIG_LOG_CONFIG_H_

// NRF_LOG module levels:
// DEBUG:    4
// INFO:     3
// WARNING:  2
// ERROR:    1
// DISABLED: 0


#define LOG_CFG_MAIN_LOG_LEVEL 4

#define LOG_CFG_BLE_COMM_LOG_LEVEL 4

#define LOG_CFG_BLE_STACK_LOG_LEVEL 4

#define LOG_CFG_ADC_LOG_LEVEL 4

#define LOG_CFG_LOGIC_LOG_LEVEL 4


#endif /* CONFIG_LOG_CONFIG_H_ */
